# Generated by Django 4.1.3 on 2022-11-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0002_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
