# Generated by Django 4.1.3 on 2022-11-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
